version: '3.8'

services:
  gacp-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.pdf
    container_name: gacp-backend-pdf
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend/logs:/app/logs
    networks:
      - gacp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/pdf/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: gacp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - gacp-backend
    networks:
      - gacp-network

networks:
  gacp-network:
    driver: bridge
