version: '3.8'

services:
  gacp-backend:
    image: node:22-alpine
    container_name: gacp-platform
    ports:
      - '5000:5000'
      - '3005:3005' # Alternative port
    volumes:
      - .:/workspace
      - /workspace/node_modules
    working_dir: /workspace/apps/backend
    command: |
      sh -c "
      echo 'Installing GACP Platform dependencies...' &&
      npm install &&
      echo 'Starting GACP Platform server...' &&
      echo 'Access Demo at http://localhost:5000/demo.html' &&
      echo 'Monitoring at http://localhost:5000/monitoring-dashboard.html' &&
      echo 'API Docs at http://localhost:5000/api/docs/docs' &&
      node atlas-server.js"
    environment:
      - NODE_ENV=development
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:5000/api/monitoring/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MongoDB for full functionality
  mongodb:
    image: mongo:7-alpine
    container_name: gacp-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=gacp2024
      - MONGO_INITDB_DATABASE=gacp_platform
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

volumes:
  mongodb_data:
